name: Deploy to IONOS Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload files via SFTP
        env:
          HOST: ${{ secrets.FTP_HOST }}
          USERNAME: ${{ secrets.FTP_USERNAME }}
          PASSWORD: ${{ secrets.FTP_PASSWORD }}
          PORT: ${{ secrets.FTP_PORT }}
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

          echo "Uploading files to IONOS server via SFTP..."

          lftp -u "$USERNAME","$PASSWORD" -p "$PORT" sftp://$HOST << EOF
          mirror -R ./ /inaya
          bye
          EOF
